language: node_js
node_js:
  - 12

services:
  - docker

script:
  - docker --version
  - docker build -t social-application ./client
  - docker tag social-application quannct/social-application:v2
after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push quannct/social-application:v2
